use sakila;
select * from actor; -- ACTOR_ID == PK 
select * from film_actor; -- ACTOR_ID == FK 
select distinct count(film_id),count(film_id) from film_actor;

SELECT A.ACTOR_ID ,A.FIRST_NAME FROM ACTOR AS A
JOIN FILM_ACTOR AS FA
WHERE A.ACTOR_ID = FA.ACTOR_ID;

SELECT * FROM FILM ; 
DESC FILM;
SELECT * FROM FILM_ACTOR;

SELECT FA.FILM_ID , FA.ACTOR_ID, F.TITLE,F.FILM_ID FROM FILM_ACTOR AS FA
JOIN FILM AS F 
WHERE FA.FILM_ID = F.FILM_ID;


SELECT F.FILM_ID, F.TITLE FROM FILM AS F;


-- ACTOR NAME AND MOVIE NAME IN WHICH ACTOR WORKED 
SELECT * FROM ACTOR; -- ACTOR ID PK 
SELECT * FROM FILM_ACTOR; -- FOREIGN KEY(ACTOR_ID) FOR ACTOR AND FILM_ID PK 
SELECT * FROM FILM; -- FILM_PK 
DESC FILM;
SELECT A.ACTOR_ID, A.FIRST_NAME, FA.FILM_ID, F.TITLE,F.FILM_ID FROM ACTOR AS A JOIN FILM_ACTOR AS FA JOIN FILM AS F WHERE A.ACTOR_ID = FA.ACTOR_ID = F.TITLE ;